services:
  app:
    build: .
    container_name: tictactoe_dev
    command: tail -f /dev/null
    ports:
      - "8888:8888"

    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    userns_mode: keep-id

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - PATH=/app/.venv/bin:$PATH

    devices:
      - /dev/dri:/dev/dri
